name: Print Secret Reference Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  print-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Print information about secret
        run: |
          echo "This workflow has access to a secret called SECRET_TOKEN"
          echo "The secret is being used but its value is masked: ${{ secrets.SECRET_TOKEN }}"
          # GitHub automatically masks secrets in logs with ***
